
import os, sys

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__))))

from import_VFCS import introduction_VFCS

"""
prompt_2_static_analysis: The second round starts with Static Analysis Feedback Analysis
"""

prompt_2_static_analysis_1 = f"""
{introduction_VFCS}

Here is the source code of the contract that needs to be tested:
"""

# will show: {source_code} in here

prompt_2_static_analysis_2 = """
For the above content, this is the result I got when I first asked a question using the large language model (LLM):

**Q&A:**
"
```md
{}
```
"
However, since the above Q&A was generated by a large language model, its accuracy cannot be ensured!

**The above content is for reference only. Do not fully trust the provided information!!!**
"""

prompt_2_static_analysis_3 = """
To ensure the generated VFCS is as accurate as possible, I used the static analysis tool Slither to analyze the given contract source code and obtained some information for reference. Please do not output content that contradicts the cautionary notes!

The static analysis results include:
1. The overall analysis report obtained by executing the command `slither [solidity file name]`. Note keywords like `Dangerous calls:` in the report!
2. The control flow graph (CFG) obtained by executing `slither [file name] --print cfg`.
3. The call graph (CG) obtained by executing `slither [file name] --print call-graph`.
4. The application binary interface (ABI) obtained by executing `solc [file name] --abi`.

**The static analysis results below are crucial for answering the subsequent questions!**
**Static Analysis Result:**
```
{}
```
"""

prompt_2_static_analysis_target = """
Based on the above "standards" — **Static Analysis Report Content**, and the critical concept of **Stateful VFCS** mentioned initially, as well as the "reference content" — **Q&A information obtained from LLM**, please answer the following questions:
(Requirement: Please include both the questions and the answers in your output, do not just output the answers without the questions)

1. What are the possible vulnerabilities or types of vulnerabilities in the current source code? (Analyze different contracts separately as there may be multiple contracts in one source code) (The types of vulnerabilities deemed impossible in the previous LLM Q&A are worth referencing)
    - output: [possible vulnerability/vulnerability type]
2. Which functions in the current source code do you think are relatively important? — Note that important functions here refer to those that are likely to cause vulnerabilities. If the function you determine to be important is marked as private, you should find the nearest parent function that calls this function and output the parent function instead. All functions marked as private in the source code should not be considered important functions!
Do not output any functions marked as private in the previous LLM Q&A!!
    - output: [key function names]
3. Which combinations of key function calls in the source code do you think are likely to cause vulnerabilities?
    - output: [function call sequence]
4. Which combinations of critical function calls in the current source code do you think could lead to vulnerabilities?
    - output: [function call sequence]
5. Based on the different contracts in the source code, what are the possible VFCS (Note that functions in VFCS should not be private functions mentioned in the Q&A)?
    - output: [possible VFCS]
6. In the source code, there may be multiple contracts. If there is only one contract, then that contract is the main contract. If there are multiple contracts, please determine which one is the main contract and output its name.
    - output: [main contract name]
"""
